### ISSUE TITLE
New clear filters button display issue

### ISSUE THREAD

**Issue by LVerhulst4321** [lostcarpark/conclar#110] opened 2022-08-10 02:34 UTC
The new clear filters icon/button will display badly depending on the screen size.
It will overlap with the search box.
It's probably only a css change that is needed, but I don't know what css setting that would be.

![image](https://user-images.githubusercontent.com/25570607/183797637-9cf534fc-5837-45f3-988f-a82773bedf1d.png)

**Comment by lostcarpark** [comment] 2022-08-10 07:26
Hmmm, that's a tricky one. Any CSS experts on the team we can ask for help?

**Comment by mcdemarco** [comment] 2022-08-10 16:13
I can take a look.

**Comment by LVerhulst4321** [comment] 2022-08-10 16:52
I've tried a few things, but I'm just shooting in the dark. :-P

**Comment by mcdemarco** [comment] 2022-08-10 20:20
I'm not seeing this behavior on main using the old config data (live from zambia.octocon.com, due to an issue I mentioned in PR#107).  Can you reproduce it with the old data, and/or give me a sample of your current data that causes it?

**Comment by LVerhulst4321** [comment] 2022-08-10 20:21
Check out https://conclar.conreg.org

**Comment by mcdemarco** [comment] 2022-08-10 20:56
> Check out https://conclar.conreg.org

Thanks!  I see some bad behavior, though not exactly the same thing.  It should be enough to work with for now.

**Comment by lostcarpark** [comment] 2022-08-10 21:38
I accidentally checked in a config file referencing local data files. I've submitted a PR to put back the previous ones. Could someone approve, please?

**Comment by lostcarpark** [comment] 2022-08-10 21:55
I've had a friend who works in UI design take a look and she suggests turning the X into a regular button and moving below the filters, which would solve the problem. What do you think?

**Comment by LVerhulst4321** [comment] 2022-08-10 22:07
A little button that says "Clear" or "Reset" would be nice.

**Comment by neo-archaic** [comment] 2022-08-10 22:51
This is the kind of UI I have in mind: https://fingalppn.ie/policy-hub/

**Comment by lostcarpark** [comment] 2022-08-10 23:56
I have uploaded the proposed change to https://conclar.conreg.org/

**Comment by LVerhulst4321** [comment] 2022-08-11 02:51
I like it.

**Comment by neo-archaic** [comment] 2022-08-11 09:22
Works well

**Comment by lostcarpark** [comment] 2022-08-11 09:36
Resolved by #112.

**Closed** 2022-08-11 09:37 UTC

**Comment by mcdemarco** [comment] 2022-08-11 20:30
> I have uploaded the proposed change to https://conclar.conreg.org/

Nice!  I would say "Clear filters" rather than "Reset filters" because it's clearer (pardon the pun).  Also, I'd style it like the Expand/Collapse buttons, though maybe a bit bigger than them; the current style is a bit...imposing when it appears.

**Comment by neo-archaic** [comment] 2022-08-11 20:42
Clear Filters would be my preferred label also, but styling it like the expand/collapse buttons is not great for UX, as it confuses the two types of interface components. Also a bigger button is more clear. For my Octocon branding fork (in progress), I'm working on making all the UI elements larger for accessibility (except for the main buttons, which are fine as they are).

**Comment by lostcarpark** [comment] 2022-08-12 00:38
The label is configurable in the config.json file, so up to the site implementor. However, if the consensus is for "Clear filters", I could make that the default
